### ISSUE TITLE
Add package to pypi

### ISSUE THREAD

**Issue by mszacun** [wwwiiilll/pyxlsb#1]
Is it possible to add this package to PyPI?

**Comment by wwwiiilll** [comment]
Yes, I believe this was way overdue, I published it on PyPI `pip install pyxlsb`

**Comment by mszacun** [comment]
Hi!,

Thank you for quick response. This package is really great. I am using buildout in my project and it has a problem with .tar.gz packages. Is it possible to upload it in wheel or egg format?

**Comment by wwwiiilll** [comment]
Well, I did upload a wheel version: `pyxlsb-1.0.1-py2.py3-none-any.whl`
