### ISSUE TITLE
chinese garbled

### ISSUE THREAD

**Issue by lves-han** [wwwiiilll/pyxlsb#11]
hi,
when I use pyxlsb to read something include chinese, it's always return garbled code of chinese. And I can't mend it with coding like gbk or utf8 or gb18030. How can I do ?

**Comment by wwwiiilll** [comment]
Things are decoded as latin-1 right now.

I've started adding more flexibility for the encoding used but it's not quite there yet.

**Comment by wwwiiilll** [comment]
@lves-han @DavidCooper since this was a simple fix, I've released v1.0.4 on PyPI fixing this issue, you should be able to update your dependencies

**Comment by DavidCooper** [comment]
Many thanks!
