### ISSUE TITLE
Create pip release of v1.1.0

### ISSUE THREAD

**Issue by elwinarens** [wwwiiilll/pyxlsb#17]
Latest version v1.0.4 contains a  `pandoc` environment dependency to run `setup.py`. This dependency seems removed in the HEAD of master and the setup.py there has version `1.1.0`.

Would you mind creating a pip release? I'm running into an issue where a remote blackbox environment runs `setup.py` and breaks on this dependency.

**Comment by wwwiiilll** [comment]
I don't feel like 1.1.0 is ready yet, however I'll consider making an alpha release

**Comment by wwwiiilll** [comment]
I've created a 1.0.5 release which should build without pandoc.

**Comment by elwinarens** [comment]
Many thanks!
