### ISSUE TITLE
'utf-16-le' codec can't decode bytes in position 0-1: illegal encoding

### ISSUE THREAD

**Issue by zenithbb** [wwwiiilll/pyxlsb#18]
for one xlsx file, can't be read 
raise the exception as in the title

'utf-16-le' codec can't decode bytes in position 0-1: illegal encoding

search the info in internet, seems similar issue as in xlrb:

https://github.com/python-excel/xlrd/issues/126

or if there is the way to override the encoding ?

**Comment by wwwiiilll** [comment]
Can you post the full traceback of the exception?

Also a small file reproducing the issue as well would help.

**Comment by zenithbb** [comment]
The small file I cannot produce, because the excel is very big and I don't know in which cell has the problem and the file content is confidential.

below is the exception 

  File "/root/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/root/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/root/BA/pyxlxb_bug_test.py", line 21, in <module>
    with open_xlsb(f'/ag03/ALNS_Geschaeftsstellen/Reporting/GU7/2019-09-02/{read_file}') as wb:

  File "/root/anaconda3/lib/python3.7/site-packages/pyxlsb/__init__.py", line 9, in open_workbook
    return Workbook(fp=zf, debug=debug)

  File "/root/anaconda3/lib/python3.7/site-packages/pyxlsb/workbook.py", line 19, in __init__
    self._parse()

  File "/root/anaconda3/lib/python3.7/site-packages/pyxlsb/workbook.py", line 44, in _parse
    self.stringtable = StringTable(fp=temp)

  File "/root/anaconda3/lib/python3.7/site-packages/pyxlsb/stringtable.py", line 9, in __init__
    self._parse()

  File "/root/anaconda3/lib/python3.7/site-packages/pyxlsb/stringtable.py", line 21, in _parse
    for item in self._reader:

  File "/root/anaconda3/lib/python3.7/site-packages/pyxlsb/reader.py", line 123, in __next__
    return self.next()

  File "/root/anaconda3/lib/python3.7/site-packages/pyxlsb/reader.py", line 174, in next
    ret = (self.handlers.get(recid) or Handler()).read(RecordReader(recdata), recid, reclen)

  File "/root/anaconda3/lib/python3.7/site-packages/pyxlsb/handlers.py", line 43, in read
    val = reader.read_string()

  File "/root/anaconda3/lib/python3.7/site-packages/pyxlsb/reader.py", line 75, in read_string
    return buff.decode(self._enc)

UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 0-1: illegal UTF-16 surrogate

**Comment by wwwiiilll** [comment]
Considering that xlrd issue, it's possible that we're seeing something similar here where an invalid file fails to parse.

You could use `open_workbook(..., debug=True)` to try to isolate the invalid value (actually, it'll fail before outputting it, but then you'd have where in the shared string table file it's failing) or add some statements around the string decoding https://github.com/wwwiiilll/pyxlsb/blob/v1.0.5/pyxlsb/reader.py#L75.

**Comment by zenithbb** [comment]
add debug=True will cause: call SyntaxError: invalid syntax

**Comment by wwwiiilll** [comment]
That's odd, it should be valid syntax.

Otherwise, can you try running this script on the file, it's a little debug utility I just drafted: https://gist.github.com/wwwiiilll/1c82fd67843162d1b581ce623dac54fe.
Just invoke it with the file as argument: `python3 debug.py somefile.xlsb`
It should dump the data of the record that's failing to parse, it will only be a single cell's internal value, you can post the output here or you can send it to me by email (willtur.will at gmail dot com) if you prefer.

**Comment by zenithbb** [comment]
sorry for late reply, below is the dump result

Exception: 'utf-16-le' codec can't decode bytes in position 0-1: illegal UTF-16 surrogate
Position: 0x510C21
ID: 19 (handler <pyxlsb.handlers.StringInstanceHandler object at 0x7f816eab4cc0>)
Length: 9
Data:
00 02 00 00 00 17 D8 0B 00

**Comment by wwwiiilll** [comment]
I created a minimal file with that data and Excel doesn't actually complain, but also doesn't render anything intellegible:
![image](https://user-images.githubusercontent.com/1878110/65741429-02fa2e80-e0ba-11e9-9535-3d5e42694b1f.png)

So this really seems like a case of broken data just like that xlrd issue referenced earlier. I guess the best that could be done with pyxlsb is to use lossy decoding and ignore invalid codepoints if that happens to kind of emulate Excel's behavior.

**Comment by wwwiiilll** [comment]
Shipped in 1.0.6
