### ISSUE TITLE
Add __version__ with the package version

### ISSUE THREAD

**Issue by TomAugspurger** [wwwiiilll/pyxlsb#22]
In https://github.com/pandas-dev/pandas/pull/29836, pandas is adding support for reading xlsb files, using pyxlsb as an engine. One difficulty we're having is that we can't check what version of pyxlsb is imported.

PEP 396 recommends a top-level `__version__`: https://www.python.org/dev/peps/pep-0396/. Could you add that to the package?

**Comment by wwwiiilll** [comment]
Sure, that's simple enough, I wasn't aware of PEP 396. I'll cut a new v1.0.6 with it so you can move forward.

**Comment by wwwiiilll** [comment]
v1.0.6 is up on PyPI
