### ISSUE TITLE
Retain date (format) values when reading from xlsb

### ISSUE THREAD

**Issue by jmilagroso** [wwwiiilll/pyxlsb#5]
Retain date (format) values when reading from xlsb instead of having numeric values:

Original cell *2-Jan-17* ~ After *42737*

**Comment by wwwiiilll** [comment]
I have to look into cell styles eventually, Excel is just formatting those numbers as readable dates.

However I don't think I'd retain the "date" format as the value, I'd instead parse it to a datetime.date/time/datetime value (exactly what the `convert_date` function does, except automatically if a date format is detected).

**Comment by jmilagroso** [comment]
Thanks!
