### ISSUE TITLE
Problem to get first sheet

### ISSUE THREAD

**Issue by minrock** [wwwiiilll/pyxlsb#7]
Hi, there is a hardcoded problem to get first sheet, as all dev can think the first way to get the first sheet is by the index 0, but there is a code to avoid this.

`    if idx < 0 or idx > len(self.sheets):
      raise IndexError('sheet index out of range')`

lines 51,52 in file workbook.py, I found this when I tried to get the first sheet with the get_sheet function from the Workbook object. 

`Traceback (most recent call last):
  File "/Users/****/virtualenvs/rollout/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-ff99215dc569>", line 1, in <module>
    workbook.get_sheet(0)
  File "/Users/****/virtualenvs/rollout/lib/python2.7/site-packages/pyxlsb/workbook.py", line 52, in get_sheet
    raise IndexError('sheet index out of range')
IndexError: sheet index out of range
`
but when I tried to get the first line as I expected then, that is using the natural index (1) for first, then I found that the file did not retrieved me the first sheet, but it retrieved me the second.

I think just allowing the index 0 in the idx variable fix the problem, will try to make a pull request with it.

Are you still maintaining this repo? let me now. 

Thanks

**Comment by wwwiiilll** [comment]
This is actually fixed in the latest master branch.

I agree that a 1-based index is awkward, I'm not sure why I thought that keeping the indices aligned with VBA was a good idea back then.

I'd like to change that back to being 0-based, but that wouldn't be backward compatible.

**Comment by minrock** [comment]
Ok, I installed from pypi, are you plannig a release soon? I appreciate your answer :) thanks

**Comment by wwwiiilll** [comment]
I went back to the 1.0.3 code and, awkwardness aside, using index 1 should have given then first sheet in the workbook. Can you double check that?

If it really doesn't work and give you the second one, then we may have something more complex than an index check.
